version: '2'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  web:
    build: .
    working_dir: /usr/src/app
    command: npm start
    ports:
      - "5001:1111"
    depends_on:
      - mongo